name: Gradle Plugin
description: Gradle plugin will allow you to launch Gradle commands to build your projects from a Clarive instance.
version: 1.0
icon: https://cdn.rawgit.com/clarive/cla-gradle-plugin/master/public/icon/gradle.svg?sanitize=true
url: https://github.com/clarive/cla-gradle-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-gradle-plugin
